language: python
cache:
  pip: true
python:
- 3.6
dist: trusty
addons:
  apt:
    packages:
    - npm
before_install:
- pip install awscli --upgrade
install: cd spa; npm install
script: make build
deploy:
- provider: script
  script: make deploy-dev-travis
  skip_cleanup: true
  on:
    branch: serverless
env:
  global:
  - secure: JMK560+jPvzcI78fKcof6ZqCsq3aSzXtH39Te/4kZyFc6h8zWyE7JXFbNgZ3HXONq7ACdEedByLP4UdgFQja+7LAXqv7Q5zXEOCTLUkNCEhZKld47HdAO5zTiR9r/30FHRrvKvwgy6oVub9/yQHLVAql0fwkhSfKnb/TCn5EGdkWQtBsWzILZWxKPL5u7Wravzxs85sr13/czfd6x99TLgZCY3QG8JVtqmQuyAzSxnOxiqIvRC52IkOqfrpzbQApezLYVKCnF7ggtl4XPfvCWINSFypxLZSHjUnUs+nH2TVVQtdBlf+u3SwLH6LMSFB9tHehaeeHk2GmlKLXAEYeyIAmaawadKLwl3s7jU62/TVVWm543Ndl1iD+6bHU3ibHm8caxvLpiQEaJ1/F3ccDnnucu3gshtJ9yHdd9A6Rh3aMyvyf4sy6KkUFqDypqLNVoDyaT+RJs3F345pMuSfyaDzClvHlJUZ8fJ94BkAYejJouKRpwuHH1YuyilovWGGu+C2kI3CagFIRKhDa2gFJbup5JFg73u/NutB1I5h6SmC7Re93ZKnEoE4jInJ4vzIg+3j83TZRRiZt/6MCfNWPIkaoUfrnJzBo3AeT0uuF6iT6yoqa1HBUA4Lr/zOOSFwcL/bCrbe0DETLuduLAMV/lIpBXncqPMEapAn9CxhF16Q=
  - secure: EQD1KZC4zQtGbpI0TTvF272KNJQq6j5nIcwJmk1d78JFNaQC+9xxXspTmFzDLn70Q7awipjdXdl6fFWfrQl9/lFuqIe4U5pHjFLEyDy7y8Ny1VCnGEXsk2YuRgrZOeopng16FmkhmpFHu5stMkf2u+7QphkV6AAqriHfT69ncDQMb/cFFO4MvbV8iKfWB0X6YWcZ/xxqfw7YQi8q/y+lxThxgtwan/LqLbVGIux5NvloOEPvLim0Kc8qfGWE0akIicYPz/FTNIFizc0VonFzKdad8yy3m1O+RVaIkXbLIyKptq9X5D3vW2ObVKMUOU6tWTP/bhEYgfceyMyli3MQFloYKqpHpKMFNfpCo7Dpp9+tCxePB4ceqJFufj2qQswpUXQQBIc45/YVRrRYBaPEhBHI32dkvGUx9C5EbFBM6TUSKtYibmB/J1v9RhU1ZOzQivlLAQXSe1s67wotRKnFwiWM4X/aZYYnZfdxUbdJ/5HYvKcJcK2wRwIj+XBQ43cEMRIIHTgS0oK+B6LDffCKOaECD++Es6lt1zshhnLpyKYLdnrQnSKdRLxlhPuhYgXuQdsdrVZDrgU2FG7VtiJwxnkrX6UH+VVAAC78rhMM6Hq9onxGPgqkutIj1iTr+pUBrmKFIe1EECQPbIn7i07WjTliLvS6UHf/lC1Ovox/PUI=
